### ISSUE TITLE
SPDK backend fails enumeration

### ISSUE THREAD

**Issue by Baekalfen** [OpenMPDK/xNVMe#127]
SPDK has an issue during enumeration, when it calls `xnvme_dev_open` here: https://github.com/OpenMPDK/xNVMe/blob/e507f2d1791163d0c2757f1b973cd2cf6dfcb573/lib/xnvme_be_spdk_dev.c#L611

It doesn't force `spdk` backend in the `opts` variable, therefore you may trigger `vfn` or another PCIe backend to try to open the device. This can happen if `spdk` fails to open the device, and `xnvme_dev_open` continues to probe other backends.

**Comment by safl** [comment]
This PR: https://github.com/OpenMPDK/xNVMe/pull/126
Should fix this for SPDK.

However, the other backends exhibit the same behavior, and probably need similar adjustments as done for SPDK on PR #126.

**Comment by safl** [comment]
Closed without merge: https://github.com/OpenMPDK/xNVMe/pull/126
This needs some renewed attention.

**Comment by karlowich** [comment]
This has been resolved by #190
