### ISSUE TITLE
Issue when opening namespace after spdk_tgt restarted on spdk backend

### ISSUE THREAD

**Issue by LiadOz** [OpenMPDK/xNVMe#210]
### How to reproduce
spdk setup:
```bash
./build/bin/nvmf_tgt
./scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a  127.0.0.1 -s 4420
./scripts/rpc.py bdev_null_create Null0 8589934592 4096
./scripts/rpc.py bdev_null_create Null1 8589934592 4096
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null0
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null1
```
A program opens namespace 1, then spdk restarts with the same setup, after that the program tries to open namespace 2.

### Explanation:
Since the controller of namespace 1 is in a bad state, when opening namespace 2, it fails to reuse the ctrlr and will either fail opening or will try to probe the device, which will modify the cref list and cause unwanted behavior.

### Suggested solution
It was suggested to me on spdk slack channel to add `spdk_nvme_ctrlr_reset` when detecting a failed controller, this allows namespace 2 to connect while keeping the same controller.
Another thing I needed to modify is to not close io qpairs from the previous controllers since they have already been closed.
Also I added a function `_verify_ctrlr_ok` that sends a keep alive admin command to make sure there is communication to the storage device, this command may be changed to any other simple admin command such as fetching log page.
I have pushed a fix suggestion #209, the changes are not trivial and may warrant a discussion.

**Comment by karlowich** [comment]
Closing this, as #209 has been merged
