### ISSUE TITLE
Some `xnvme_` functions are not place correctly in docs

### ISSUE THREAD

**Issue by metaspace** [OpenMPDK/xNVMe#239]
https://xnvme.io/docs/latest/capis/xnvme.html#xnvme-enumeration-alloc xnvme_enumeration_alloc() appears to be part of libxnvme.h but it is actually in libxnvmec.h.

Documentation generator uses function prefix to place functions. `xnvme_enumeration_alloc()` lives in libxnvmec.h but has wrong prefix.

**Comment by karlowich** [comment]
Closing this due to #242 being merged
