### ISSUE TITLE
win10 install fail

### ISSUE THREAD

**Issue by Jojo-moon** [OpenMPDK/xNVMe#246]
![0c74b5f9-deb9-4e07-b538-4b6dad1b65bf](https://user-images.githubusercontent.com/22465863/219295151-b884e97c-0f58-4797-8fdd-f54a6665891d.jpg)
![0c74b5f9-deb9-4e07-b538-4b6dad1b65bf](https://user-images.githubusercontent.com/22465863/219295192-24ef0a5c-2ac4-4ba7-9f66-bb171a837603.jpg)

**Comment by rs-sam** [comment]
Hi @Jojo-moon, Thanks for posting your query here.
I can see meson is using 'gcc' compiler but xNVMe-windows is based on clang compiler. Please refer to the 'toolbox/pkgs/windows-2019.bat' script to ensure that required build toolchain is installed on your machine.

**Comment by karlowich** [comment]
Hi @Jojo-moon, 
It seems you have found a bug in our build system, thanks!
I have created a PR to fix the bug, please try it out: #247 

However, please also follow the advice of @rs-sam :)

**Comment by Jojo-moon** [comment]
I had tried #247 ,However, errors will still be reported when installing fio. So i ask for help.

![061ff7c1-4855-4459-8941-4438a52085cb](https://user-images.githubusercontent.com/22465863/219622671-12ae9648-d176-44f7-9d4b-b0e705d78c93.jpg)

**Comment by Jojo-moon** [comment]
> I had tried #247 ,However, errors will still be reported when installing fio. So i ask for help.
> 
> ![061ff7c1-4855-4459-8941-4438a52085cb](https://user-images.githubusercontent.com/22465863/219622671-12ae9648-d176-44f7-9d4b-b0e705d78c93.jpg)

I had tried https://github.com/OpenMPDK/xNVMe/pull/247 ,However, errors will still be reported when installing fio. So i ask for help.

061ff7c1-4855-4459-8941-4438a52085cb

**Comment by Jojo-moon** [comment]
> I had tried #247 ,However, errors will still be reported when installing fio. So i ask for help.
> 
> ![061ff7c1-4855-4459-8941-4438a52085cb](https://user-images.githubusercontent.com/22465863/219622671-12ae9648-d176-44f7-9d4b-b0e705d78c93.jpg)

I had tried https://github.com/OpenMPDK/xNVMe/pull/247 ,However, errors will still be reported when installing fio. So i ask for help.

061ff7c1-4855-4459-8941-4438a52085cb

**Comment by Jojo-moon** [comment]
> Hi @Jojo-moon, It seems you have found a bug in our build system, thanks! I have created a PR to fix the bug, please try it out: #247
> 
> However, please also follow the advice of @rs-sam :)

I had tried https://github.com/OpenMPDK/xNVMe/pull/247 ,However, errors will still be reported when installing fio. So i ask for help.

061ff7c1-4855-4459-8941-4438a52085cb

**Comment by rs-sam** [comment]
Hi @Jojo-moon 
Have you tried running 'toolbox/pkgs/windows-2019.bat' batch on your machine? It will install the required tools and packages.

If you are facing any issue, packages can be installed manually using MSYS2 terminal.
1. C compiler for the host machine should be 'clang'
   clang package can be installed using 'pacman -S mingw-w64-x86_64-clang' under MSYS2 terminal.
2. FIO build system for windows is based on cygwin
    chocolatey based 'make.exe' is build for windows, to build FIO MSYS based 'make.exe' will be required to do cross- 
    compilation.
    make package can be installed using 'pacman -S mingw-w64-x86_64-make' under MSYS2 terminal.

Adding a screenshot for your reference, to see the tools and its paths, 
![1](https://user-images.githubusercontent.com/80966426/220038368-f1bf56cf-6a7f-4dd8-a650-769e1a2ba660.PNG)

**Comment by Jojo-moon** [comment]
> Hi @Jojo-moon Have you tried running 'toolbox/pkgs/windows-2019.bat' batch on your machine? It will install the required tools and packages.
> 
> If you are facing any issue, packages can be installed manually using MSYS2 terminal.
> 
> 1. C compiler for the host machine should be 'clang'
>    clang package can be installed using 'pacman -S mingw-w64-x86_64-clang' under MSYS2 terminal.
> 2. FIO build system for windows is based on cygwin
>    chocolatey based 'make.exe' is build for windows, to build FIO MSYS based 'make.exe' will be required to do cross-
>    compilation.
>    make package can be installed using 'pacman -S mingw-w64-x86_64-make' under MSYS2 terminal.
> 
> Adding a screenshot for your reference, to see the tools and its paths, ![1](https://user-images.githubusercontent.com/80966426/220038368-f1bf56cf-6a7f-4dd8-a650-769e1a2ba660.PNG)

I had run windows-2019.bat always. I had do following steps :

Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

   cd toolbox\pkgs
   windows-2019.bat
   cd xnvme
   meson setup builddir (failed as above)

**Comment by Jojo-moon** [comment]
> Hi @Jojo-moon Have you tried running 'toolbox/pkgs/windows-2019.bat' batch on your machine? It will install the required tools and packages.
> 
> If you are facing any issue, packages can be installed manually using MSYS2 terminal.
> 
> 1. C compiler for the host machine should be 'clang'
>    clang package can be installed using 'pacman -S mingw-w64-x86_64-clang' under MSYS2 terminal.
> 2. FIO build system for windows is based on cygwin
>    chocolatey based 'make.exe' is build for windows, to build FIO MSYS based 'make.exe' will be required to do cross-
>    compilation.
>    make package can be installed using 'pacman -S mingw-w64-x86_64-make' under MSYS2 terminal.
> 
> Adding a screenshot for your reference, to see the tools and its paths, ![1](https://user-images.githubusercontent.com/80966426/220038368-f1bf56cf-6a7f-4dd8-a650-769e1a2ba660.PNG)
> 
> Note: Use 'build.bat' in xnvme folder to start complilation.

I had built xnvme successfully by pulling next branch code ,thanks!

**Comment by safl** [comment]
Thanks @karlowich and @rs-sam for helping out @Jojo-moon !
@Jojo-moon looks like your issue is resolved. In case it is not, then feel free to re-open.
