### ISSUE TITLE
fio use external io engine fail on ubuntu 20.04

### ISSUE THREAD

**Issue by Jojo-moon** [OpenMPDK/xNVMe#248]
![21cad3ea-6031-4f7e-af36-c3ae640b4cd2](https://user-images.githubusercontent.com/22465863/219618677-5843f4d0-27c3-46e9-a6bd-14b3d5071305.jpg)

By the way,does xnvme support Android system？

**Comment by safl** [comment]
This happens when using the external xnvme io-engine with a version of fio which has support for the internal xnvme io-engine. So you can choose:

* instead of using the external engine, then use the internal one
* build fio without the internal engine and then use the external engine.

**Comment by safl** [comment]
We are not testing on Android, but i do not see a reason why xnvme should not work ln Android.

**Comment by Jojo-moon** [comment]
> We are not testing on Android, but i do not see a reason why xnvme should not work ln Android.



> This happens when using the external xnvme io-engine with a version of fio which has support for the internal xnvme io-engine. So you can choose:
> 
> * instead of using the external engine, then use the internal one
> * build fio without the internal engine and then use the external engine.

I don't quite understand. I have the following confusion.

1. I installed xnvme, but the command line could not find fio. I installed fio additionally before, but I see that xnvme has subproject fio. Do you know if xnvme has installed fio? Do I need to install fio additionally?

2. fio has supported internal xnvme io engine. What does it mean?

**Comment by ankit-sam** [comment]
Hi @Jojo-moon

We have both the external and internal xnvme fio engine
- The external fio engine is any engine which is not bundled with the fio source code. The external xnvme fio engine is present in xNVMe repo at tools/fio-engine/xnvme_fioe.c.
- Any internal fio engine is the one which is there with the fio source code. The internal xnvme fio engine is present in fio repo at engines/xnvme.c

what @safl mentioned is that:

[2]. you can try and use external fio engine, and it will require you to disable the internal fio engine.
Command to disable internal fio engine and building fio is:

```./configure --disable-xnvme```
```make && make install```

[1]. or you can use the internal fio engine, sample configuration file can be found here:
https://github.com/axboe/fio/blob/master/examples/xnvme-compare.fio

We will soon remove the external xnvme fio engine, and are currently waiting for a newer version of fio release.

**Comment by karlowich** [comment]
Hi @Jojo-moon, is this solved?
Then I will close this issue.
