### ISSUE TITLE
win10 build fail sometimes and install fail

### ISSUE THREAD

**Issue by Jojo-moon** [OpenMPDK/xNVMe#258]
1 .run build.bat will  sometimes hold  :
![Capture](https://user-images.githubusercontent.com/22465863/223664966-03cec075-ea28-4113-8c24-378762c92507.PNG)

2 . is this a  problem:

![Capture](https://user-images.githubusercontent.com/22465863/223663068-3a167807-ab66-4aad-bbcc-30fa03532098.PNG)

3. I can not execute xnvme commands in any path automatically. I just add exe file path to system path manually  :

![Capture](https://

4. I send  vs command with opcode=0xC1

   
![Capture](https://user-images.githubusercontent.com/22465863/223683157-f42c2513-b980-43b4-9bb5-b29197653beb.PNG)

**Comment by karlowich** [comment]
Hi @Jojo-moon, regarding your points:
1. This is perfectly fine

2. This is a problem, yes. However, your screenshot makes it hard to see what went wrong. Which branch are you on?

3. It is expected that you have to add to your PATH before being able to run xnvme commands.
In the CI we add these to PATH:
```set "PATH=%SystemDrive%\tools\msys64;%PATH%"
  set "PATH=%SystemDrive%\tools\msys64\usr\bin;%PATH%"
  set "PATH=%SystemDrive%\tools\msys64\mingw64\bin;%PATH%"
  ```
  
4. This is likely a problem with your `cmd-out.nvmec` and not xNVMe. 
The Microsoft NVMe driver doesn't support pass-through.
@rs-sam do you have a solution for this?

**Comment by Jojo-moon** [comment]
> Hi @Jojo-moon, regarding your points:
> 
> 1. This is perfectly fine
> 2. This is a problem, yes. However, your screenshot makes it hard to see what went wrong. Which branch are you on?
> 3. It is expected that you have to add to your PATH before being able to run xnvme commands.
>    In the CI we add these to PATH:
> 
> ```
> set "PATH=%SystemDrive%\tools\msys64;%PATH%"
> set "PATH=%SystemDrive%\tools\msys64\usr\bin;%PATH%"
> set "PATH=%SystemDrive%\tools\msys64\mingw64\bin;%PATH%"
> ```
> 
> 4. This is likely a problem with your `cmd-out.nvmec` and not xNVMe.
>    The Microsoft NVMe driver doesn't support pass-through.
>    @rs-sam do you have a solution for this?

1. on main branch ,however next branch may be the same.
2.  I just run test_padc with opcode=0xc1,others not change.  I tried test padc with opcode=0x6 ,it works!

**Comment by rs-sam** [comment]
Hi @Jojo-moon 
Current xNVMe Windows backend does not support pass-through commands.
There is a new option called 'STORAGE_PROTOCOL_COMMAND' that can be used to send vendor specific admin/nvme commands, xNVMe build system is based on MinGW headers and libs and this 'STORAGE_PROTOCOL_COMMAND' is not yet available in that.

**Comment by Jojo-moon** [comment]
> Hi @Jojo-moon Current xNVMe Windows backend does not support pass-through commands. There is a new option called 'STORAGE_PROTOCOL_COMMAND' that can be used to send vendor specific admin/nvme commands, xNVMe build system is based on MinGW headers and libs and this 'STORAGE_PROTOCOL_COMMAND' is not yet available in that.

I I konw STORAGE_PROTOCOL_COMMAND can be used to send vs command . Will xnvme support it later ?

**Comment by rs-sam** [comment]
Yes, it is in our bucket-list.
