### ISSUE TITLE
Correctly handle the XNVMEC_LFLG type arguments in xnvmec_assing_arg

### ISSUE THREAD

**Issue by Joelgranados** [OpenMPDK/xNVMe#272]
in xnvmec_assing_arg.
With XNVMEC_LFLG type arguments `arg` is 0x0 (because there is no accompanying arg) and `num` is always 0 because the code that sets it is skipped in line 1207.
Every time you are in a case of a XNVMEC_LFLG type arg you should have logic that handles it being in the arguments.

IMO the refactoring should be changing all the XNVMEC_LFLG type args from `args->ARG = arg ? num : 1;` to `args->ARG_NAME = 1;` or whatever should happen when the arg is present in the command line.

**Comment by karlowich** [comment]
Since #457 has been merged, I will close this.
