### ISSUE TITLE
KV Cleanup

### ISSUE THREAD

**Issue by safl** [OpenMPDK/xNVMe#288]
To move the initial support for KV along, then this issue holds notes for things to cleanup once https://github.com/OpenMPDK/xNVMe/pull/270 is integrated on ``next``.

# KV Cleanup

- [x] In ``include/libxnvme_spec.h`` there is ia reference to the TP, this should be a reference to the NVMe command-set spec. instead. ``@see TP4015a, Section 2.5, figure X1``
- [x] Migrate kv-pytests to use ctypes-bindings instead of cython
- [x] Migrate kv-pytests to use cijoe.config.options and xnvme_parametrize instead of custom device management.
- [x] In ``libxnvme_spec.h`` mention of ``@struct xnvme_spec_znd_opc`` should be ``@struct xnvme_spec_kv_opc``
- [x] Remove superfluous comment
```
 * @enum xnvme_spec_kv_status_code
 */
enum xnvme_spec_kv_status_code {
	/// Key-value Command Set
```
- [x] The below should probably be ``This should probably be changed to @see Key Value Command Set Specification Revision 1.0c, Figure 39``
```
/**
 * Key Value Command Set identify namespace data structure
 *
 * @see TP4015a, Section 3.1
```
- [x] The below should be ``This should be @struct xnvme_spdc_kvs_idfy_ns``
```
* Key Value Command Set identify namespace data structure
 *
 * @see TP4015a, Section 3.1
 * @struct xnvme_spec_ksd_idfy_ns
```
* [x] Fix duplicate xnvme-cli option:
```
{.opt = XNVMEC_OPT_KV_STORE_COMPRESS,
	 .vtype = XNVMEC_OPT_VTYPE_NUM,
	 .name = "compress",
	 .descr = "KV Store Option to compress value on device"},
```
- [x] Remove excess ``break`` statement in ``xnvme_be_dev_derive_geometry()``

Misc
====

* Provide comprehensive set of status-codes in ``include/libxnvme_spec.h``, a couple of definitions were added with PR #270, thus noted here.

**Comment by karlowich** [comment]
That `break` statement is correct in `xnvme_be_dev_derive_geometry()` it is a nested `switch` statement and thus there are two consecutive `break` statements.
