### ISSUE TITLE
Enable control of which libraries are built (shared & static)

### ISSUE THREAD

**Issue by safl** [OpenMPDK/xNVMe#326]
Currently, then libxnvme is built as a both a shared as well as a static library.
The user should be able to control this, ideally using the meson-infrastructure (default_library=shared/static/both).

The motivation for controlling this is for the intregration with xNVMe (``bdev_xnvme``) in SPDK.

**Comment by karlowich** [comment]
For SPDK, I have found a solution that does not require changes to xNVMe.
Since this is the main motivation for this, I will close this issue.
