### ISSUE TITLE
"xnvme list/enum" core dumps if set option --disable-spdk

### ISSUE THREAD

**Issue by qihui81** [OpenMPDK/xNVMe#4]
repro
1. ./configure --enable-debug --disable-be-spdk --disable-be-fbsd --disable-tools-fio;make -j4;make install
2. > xnvme list
# xnvme_enumerate()
Segmentation fault

root cause
After disabling spdk or fbsd, g_xnvme_be_registry[i]->dev of spdk & fbsd is NULL

**Comment by safl** [comment]
Thanks for reporting this, I'll take a closer look.

**Comment by safl** [comment]
A fix will be included in the next release, you can have a preview on the ``dev`` branch.

**Comment by safl** [comment]
Hi @qihui81 ,
This is fixed in: https://github.com/OpenMPDK/xNVMe/releases/tag/v0.0.22
Best,
Simon
