### ISSUE TITLE
xnvme identify controller erroneously sets nsid

### ISSUE THREAD

**Issue by Baekalfen** [OpenMPDK/xNVMe#465]
When calling `xnvme idfy --cns 1`, the `nsid` gets internally set automatically. For a Samsung 980 Pro drive, this will make the admin command fail if the `nsid` is not zero.

When calling `xnvme idfy-ctrlr`, the `nsid` is unconditionally set to `0`, which makes the admin command succeed.

**Comment by karlowich** [comment]
Since #466 has been merged, I will close this
